# You need the AZURE_WEB_APP_NAME and to download the deployment profile and
# add it as a secret to this repo with the name AZURE_WEBAPP_PUBLISH_PROFILE
name: Trigger auto deployment for demo-container

env:
  # !!!! UPDATE THESE VARIABLE BELOW !!!!
  AZURE_WEBAPP_NAME: purplevjs 
  AZURE_GROUP_NAME: purplevjs

# When this action will be executed
on:
 # push:
 #   branches:   [ main ]

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Docker hub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: build and push container to Docker Hub
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/build-push-action@v2
        with:
         context: ./
         file: ./Dockerfile
         push: true
         tags: purplevjs/week4:latest
          # username: ${{ github.actor }}
          # password: ${{ github.token }}

#
 # # deploy:
 #    runs-on: ubuntu-latest
 #    needs: build
 #    steps:
 #      - name: Azure Login
 #        uses: azure/login@v1
 #        with:
 #          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
 #      - name: Lowercase the repo name and username
 #        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
 #      - name: Configure container and registry settings
 #        uses: azure/CLI@v1
 #        with:
 #          inlineScript: |
 #            az config set extension.use_dynamic_install=yes_without_prompt
 #            az webapp config container set --docker-custom-image-name ghcr.io/${{ env.REPO }}:${{ github.sha }} --docker-registry-server-password ${{ secrets.PAT }} --docker-registry-server-user ${{ github.actor }} --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }}
 #            az webapp config appsettings set -g ${{ env.AZURE_GROUP_NAME }} -n ${{ env.AZURE_WEBAPP_NAME }} --settings WEBSITES_PORT=8000

 #      - name: Deploy to Azure Web App
 #        id: deploy-to-webapp
 #        uses: azure/webapps-deploy@v2
 #        with:
 #          app-name: ${{ env.AZURE_WEBAPP_NAME }}
 #          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
 #          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
